import os
import json
import re
import zipfile
from pathlib import Path
import aria.memory as memory
import aria.llm as llm
from aria.tools.executor import execute_python_script

BUILDER_SYSTEM_PROMPT = """You are ARIA's Agent Builder. Your goal is to generate a fully working, runnable Python agent according to Mehedi's requirements.

Standard Agent Folder Structure:
- main.py (Entry point)
- agent.py (Core agent logic)
- config.py (Configuration / API key loader from .env)
- tools/ (Subdirectory for tools)
  - __init__.py
  - [tool_name].py (Individual tool modules)
- memory/ (Optional subdirectory for persistent state/memory)
  - store.py (SQLite or file-based memory)
- .env.example (Environment variables template)
- requirements.txt (Dependencies list)
- README.md (Setup instructions, how to run, dependencies, environment keys)

Rules for Agent Generation:
1. Every script must be complete, syntax-correct, and runnable. No placeholders, no pseudocode.
2. Load all settings/credentials from config.py which pulls from os.environ (via python-dotenv).
3. Provide robust error handling and clear console log outputs using print() or logging.
4. Output your response as a single valid JSON block enclosing all files. The structure must be:
{
  "agent_name": "snake_case_name",
  "description": "Brief summary of what the agent does",
  "files": {
     "file_relative_path": "complete file content"
  }
}

Example output structure:
```json
{
  "agent_name": "arxiv_monitor",
  "description": "Monitors arXiv for continual learning papers and sends Telegram summaries",
  "files": {
    "config.py": "...",
    "requirements.txt": "...",
    "main.py": "..."
  }
}
```
Only return the raw JSON block. Do not write explanations outside the JSON block. Do not use markdown syntax wrapping the JSON block unless it is inside triple backticks (```json).
"""

def extract_json_block(text: str) -> dict:
    """Extracts and parses JSON object from LLM response text."""
    # Find JSON blocks wrapped in backticks or raw
    match = re.search(r"```json\s*(.*?)\s*```", text, re.DOTALL)
    if match:
        json_str = match.group(1).strip()
    else:
        # Fallback to looking for the first { and last }
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end != -1:
            json_str = text[start:end+1].strip()
        else:
            json_str = text.strip()
            
    # Remove any control characters or leading/trailing noise
    return json.loads(json_str)

def build_agent(user_request: str) -> str:
    """Main function to parse instruction, generate agent code, package it, and verify it."""
    print("  [ARIA Agent Builder: Generating agent plan and code...]", flush=True)
    
    # Query LLM for code generation
    prompt = f"Request: {user_request}\n\nGenerate the complete Python agent files."
    llm_output = llm.generate_response(
        f"{BUILDER_SYSTEM_PROMPT}\n\n{prompt}", 
        history=[] # Fresh session for agent builder tasks
    )
    
    try:
        agent_data = extract_json_block(llm_output)
    except Exception as e:
        return f"Error: Failed to parse generated agent code as JSON. Raw output:\n{llm_output}\nError details: {e}"
        
    agent_name = agent_data.get("agent_name", "custom_agent").strip().lower()
    # Replace spaces with underscores
    agent_name = re.sub(r"\s+", "_", agent_name)
    description = agent_data.get("description", "A custom Python agent built by ARIA")
    files = agent_data.get("files", {})
    
    if not files:
        return "Error: No files generated by the Agent Builder."
        
    # Resolve workspace paths
    workspace_root = Path(memory.get_db_connection().execute("SELECT value FROM profile WHERE key='portfolio'").connection.row_factory(None, None) or Path(__file__).resolve().parent.parent.parent)
    # Let's write the generated agents into a 'built_agents' folder inside the workspace
    workspace_root = Path(__file__).resolve().parent.parent
    agents_dir = workspace_root / "built_agents" / agent_name
    agents_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"  [ARIA Agent Builder: Writing files to {agents_dir}...]", flush=True)
    
    # Write files to target folder
    for rel_path, content in files.items():
        file_path = agents_dir / rel_path
        # Ensure parent directories exist (e.g. tools/, memory/)
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
    # Verify syntax of main files
    print("  [ARIA Agent Builder: Verifying syntax of generated files...]", flush=True)
    compilation_error = None
    for file_path in agents_dir.glob("**/*.py"):
        # Compile syntax check using compileall or simple test run
        check_res = execute_python_script(str(file_path), args=["--help"], timeout=5)
        # Check stderr for syntax error (compile check fails)
        if "SyntaxError" in check_res["stderr"]:
            compilation_error = f"Syntax error in {file_path.name}: {check_res['stderr']}"
            break
            
    if compilation_error:
        print(f"  [Warning: {compilation_error}]", flush=True)
        
    # Create ZIP archive
    zip_path = workspace_root / "built_agents" / f"{agent_name}.zip"
    print(f"  [ARIA Agent Builder: Packaging agent into {zip_path}...]", flush=True)
    
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files_in_dir in os.walk(agents_dir):
            for file in files_in_dir:
                file_full_path = Path(root) / file
                arcname = file_full_path.relative_to(agents_dir)
                zipf.write(file_full_path, arcname)
                
    # Register the agent in memory index
    memory.add_built_agent(agent_name, description, str(agents_dir))
    
    # Return completion report
    report = f"""### 🤖 Agent Built Successfully: **{agent_name}**

**Description**: {description}  
**Location**: `{agents_dir}`  
**Download Package**: [built_agents/{agent_name}.zip](file://{zip_path})  

---

#### 📁 Project Files Generated:
"""
    for rel_path in files.keys():
        report += f"- `{rel_path}`\n"
        
    report += f"""
---

#### 🚀 How to Run the Agent:
1. Navigate to the agent directory:
   ```bash
   cd built_agents/{agent_name}
   ```
2. Install the required dependencies:
   ```bash
   pip install -r requirements.txt
   ```
3. Configure your keys/secrets:
   ```bash
   cp .env.example .env
   ```
   *(Open `.env` and fill in the missing API keys)*
4. Execute the agent:
   ```bash
   python main.py
   ```
"""
    if compilation_error:
        report += f"\n> ⚠️ **Notice**: {compilation_error}"
        
    return report
